# Generated by Django 5.2.4 on 2025-07-29 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('wake_up_meal', models.BooleanField(default=False)),
                ('breakfast', models.BooleanField(default=False)),
                ('snack', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('evening_snack', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
                ('bedtime_meal', models.BooleanField(default=False)),
                ('workout_done', models.BooleanField(default=False)),
                ('workout_type', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
