# Generated by Django 5.2.4 on 2025-07-30 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('water_intake', models.IntegerField(default=0)),
                ('wake_up', models.BooleanField(default=False)),
                ('breakfast', models.BooleanField(default=False)),
                ('snack', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('evening_snack', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
                ('bedtime', models.BooleanField(default=False)),
                ('workout_done', models.BooleanField(default=False)),
                ('workout_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('gain', 'Weight Gain'), ('lose', 'Weight Loss')], max_length=10)),
                ('current_weight', models.FloatField()),
                ('target_weight', models.FloatField()),
                ('water_goal', models.IntegerField(default=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DailyEntry',
        ),
    ]
