# Generated by Django 5.2.4 on 2025-07-30 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0002_dailylog_userprofile_delete_dailyentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('goal', models.CharField(choices=[('gain', 'Weight Gain'), ('loss', 'Weight Loss')], max_length=10)),
                ('weight', models.FloatField(help_text="Today's weight in kg")),
                ('waking_meal', models.TextField(blank=True, null=True)),
                ('breakfast', models.TextField(blank=True, null=True)),
                ('mid_morning_snack', models.TextField(blank=True, null=True)),
                ('lunch', models.TextField(blank=True, null=True)),
                ('evening_snack', models.TextField(blank=True, null=True)),
                ('dinner', models.TextField(blank=True, null=True)),
                ('before_bed', models.TextField(blank=True, null=True)),
                ('workout', models.TextField(blank=True, null=True)),
                ('water_intake', models.PositiveIntegerField(help_text='Water intake in ml')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DailyLog',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
