# Generated by Django 5.2.4 on 2025-07-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0004_dailyprogress_dietplan_watertarget_workoutplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watertarget',
            name='measurement_type',
            field=models.CharField(choices=[('glass', 'Glass'), ('bottle', 'Bottle')], default='glass', max_length=10),
        ),
        migrations.AddField(
            model_name='watertarget',
            name='quantity_per_day',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watertarget',
            name='unit_volume_ml',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='watertarget',
            name='daily_goal_ml',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
