# Generated by Django 5.2.4 on 2025-07-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0008_alter_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
