# Generated by Django 5.2.4 on 2025-07-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0009_alter_userprofile_height_cm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyprogress',
            name='workout_completed',
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='completed_foods',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='completed_workouts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='today_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
