# Generated by Django 5.2.4 on 2025-10-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0011_dailyjournal_dailyroutine'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogress',
            name='completed_routines',
            field=models.JSONField(default=list),
        ),
    ]
