# Generated by Django 5.2.4 on 2025-11-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0012_dailyprogress_completed_routines'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyRoutine',
        ),
    ]
