# Generated by Django 5.2.4 on 2025-11-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0015_dietplan_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
