# Generated by Django 5.2.4 on 2025-11-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0016_workoutplan_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyroutine',
            name='is_auto',
            field=models.BooleanField(default=False),
        ),
    ]
